name: recipe_app
description: A recipe app copy

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  localstorage: ^3.0.3+6
  dotted_border: ^1.0.6
  provider: ^4.3.2+2
  file: ^5.2.1
  flutter_image: ^3.0.0
  mongo_dart: ^0.4.4
  crypto: ^2.1.5
  flushbar: ^1.10.4
  async: ^2.4.2
  path_provider: ^1.6.24
  flutter_absolute_path: ^1.0.6
  flutter_image_compress: ^0.7.0
  file_picker: ^2.1.0
  path: any
  simple_animations: ^2.4.2
  flutter_localizations:
    sdk: flutter
  speech_to_text: ^2.7.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/ingredient.json
    - assets/data/recipe.json
    - assets/상세창/
    - assets/ingredients/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
